name: depth_gait_env
channels:
  - defaults
dependencies:
  - astroid=2.0.4=py37_0
  - atomicwrites=1.2.1=py37_0
  - attrs=18.2.0=py37h28b3542_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - cloudpickle=0.6.1=py37_0
  - coverage=4.5.1=py37h14c3975_0
  - cycler=0.10.0=py37_0
  - dask-core=0.20.2=py37_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py37_0
  - expat=2.2.6=he6710b0_0
  - flake8=3.5.0=py37_1
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hypothesis=3.68.0=py37h39e3cac_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.4.1=py37_0
  - intel-openmp=2019.0=118
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.0.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.4=py37_0
  - jedi=0.13.1=py37_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.2.3=py37_0
  - jupyter_core=4.4.0=py37_0
  - kiwisolver=1.0.1=py37hf484d3e_0
  - lazy-object-proxy=1.3.1=py37h14c3975_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - matplotlib=3.0.0=py37h5429711_0
  - mccabe=0.6.1=py37_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - more-itertools=4.3.0=py37_0
  - ncurses=6.1=hf484d3e_0
  - networkx=2.2=py37_1
  - numpy=1.15.4=py37h1d66e8a_0
  - numpy-base=1.15.4=py37h81de0dd_0
  - olefile=0.46=py37_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py37h04863e7_0
  - parso=0.3.1=py37_0
  - patsy=0.5.0=py37_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.3.0=py37h34e0f95_0
  - pip=18.1=py37_0
  - pluggy=0.7.1=py37h28b3542_0
  - prompt_toolkit=2.0.6=py37_0
  - ptyprocess=0.6.0=py37_0
  - py=1.6.0=py37_0
  - pycodestyle=2.4.0=py37_0
  - pydocstyle=3.0.0=py37_0
  - pyflakes=1.6.0=py37_0
  - pygments=2.2.0=py37_0
  - pylint=2.1.1=py37_0
  - pyparsing=2.2.2=py37_0
  - pyqt=5.9.2=py37h05f1152_2
  - pytest=3.8.2=py37_0
  - python=3.7.0=h6e4f718_3
  - python-dateutil=2.7.3=py37_0
  - pytz=2018.5=py37_0
  - pywavelets=1.0.1=py37hdd07704_0
  - pyzmq=17.1.2=py37h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.0=py37h4989274_1
  - scipy=1.1.0=py37hfa4b5c9_1
  - setuptools=40.4.3=py37_0
  - simplegeneric=0.8.1=py37_2
  - sip=4.19.8=py37hf484d3e_0
  - six=1.11.0=py37_1
  - snowballstemmer=1.2.1=py37_0
  - sqlite=3.25.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py37_0
  - tornado=5.1.1=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.32.1=py37_0
  - wrapt=1.10.11=py37h14c3975_2
  - xlrd=1.1.0=py37_1
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - pip:
    - dask==0.20.2
    - opencv-python==3.4.3.18
prefix: /home/andrew/anaconda3/envs/depth_gait_env

